pages:
    stage: deploy
    
    script:
    - mkdir .public
    - cp -a all-panels .public
    - cp -a example* .public
    - cp -a *.js .public
    - cp -a index.html .public
    - cp -a *.css .public
    - cp -a README.md .public
    - mv .public public

    artifacts:
        paths:
        - public
    
    only:
    - master
